# Generated by Django 4.1.7 on 2023-03-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="content",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
